PUT https://whatbytes-assignment-ds1d.onrender.com/api/patients/b0160b4e-0d72-4dfa-a2a8-0df6253b4f42
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwNWNhOWU4LTI0NDQtNDY1ZC1iYjM5LWZjMDZmNTM1YTQ2NiIsImVtYWlsIjoidmlzaGVzaEBleGFtcGxlLmNvbSIsImlhdCI6MTc1NzA5NDE0OSwiZXhwIjoxNzU3NTI2MTQ5fQ.8gPhhnjcNQYbbz3X4Fr-_gmhWU2ZvVzZKtXmAZZoOf8

{
  "name": "Rohan Gupta Updated",
  "phone": "9988776655"
}